name: GHPages

on:
  push:
    branches: [main]

jobs:
  deploy-docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Packages
        run: yarn
      - name: Build docs
        run: |+
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          force_orphan: true
